import BottomNav from "@/components/BottomNav";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { AuthProvider } from "@/context/AuthContext";
import { CartProvider } from "@/context/CartContext";
import { theme } from "@/theme/antd";
import ApolloClientProvider from "@/utils/ApolloClientProvider";
import { hindSiliguriFonts } from "@/utils/customFonts";
import UserSessionProvider from "@/utils/UserSessionProvider";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "animate.css";
import { ConfigProvider } from "antd";
import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <UserSessionProvider>
      <ConfigProvider theme={theme}>
        <html lang="en">
          <body
            className={`${hindSiliguriFonts.variable} font-hindSiliguri antialiased`}
          >
            <AuthProvider>
              <Toaster />
              <ApolloClientProvider>
                <CartProvider>
                  <AntdRegistry>
                    <Header />
                    {children}
                    <Footer />
                    <BottomNav />
                  </AntdRegistry>
                </CartProvider>
              </ApolloClientProvider>
            </AuthProvider>
          </body>
        </html>
      </ConfigProvider>
    </UserSessionProvider>
  );
}
